---
layout: post
title: JS강의노트_예외처리, REST API, npm, npx, .gitignore
category: Javascript
permalink: /Javascript/:title/

tags: [자바스크립트]
comments: true
---

# 예외처리 (exception handling)
문법에러(프로그래머 실수), 네트워크 에러등

>동기식 / 비동기식(ex. fetch)의 에러코드는 양상이 다르다.
```js
// 1. 동기식 코드 에러
// js엔진이 호출스택을 rewind한다
RangeError: Invalid array length
    at c:8:3
    at b:5:3
    at a:2:3
    at eval:1:1
    at eval

// 2. 비동기식 코드 에러
main.95a2accdd2e8d85ddcd1.bundle.js:57 GET https: ..net::ERR_NAME_NOT_RESOLVED
GlitteringTightInganue:1 Uncaught (in promise) TypeError: Failed to fetch
```

## `try{...} catch(e){...}` : 예외처리
* try 블록안에 에러가능성이 있는 코드를짠다
* 에러가 나면, 에러정보가 catch의 `(e)`로 들어가고 그에따른 코드를 실행한다.
  * 에러는 `e.name`, `e.message` 라는 속성을 가지고있다

```js
try{
  new Array(-1); // RangeError : Invalid array length
}catch(e){
  alert(`다음과 같은 에러가 발생했습니다: ${e.name}: ${e.message}`);
}
```

## `try{...} finally {...}` :

* try 블록이 에러가 나던 말던, finally가 실행된다.
* 심지어 try 블록안에서 `return`, `break`, `continue`(점프)를 만나도, 멈추지않고 finally를 실행한다
* 백엔드에서는 스택의 함수가 동시에 실행되는 경우가 많아서 어떤자원을 쓰고있는지 표시해주기 위해 사용. 프론트엔 콜스택이 하나기때문에 잘 안씀
```js
for(let i of [1, 2, 3]){
  if(i === 3){
    break; //즉시종료
  }
  conaole.log(i);
} // 1, 2 출력

for(let i of [1, 2, 3]){
  try{
    if(i === 3){
      break;
    }
  } finally{
    console.log(i);
  }
} // 1, 2, 3 출력
```

> try - catch - finally 순으로 사용해야한다 !

## 직접 에러 발생시키기
라이브러리를 만드는 사람들이 에러에 따른 메시지를 주기 위해 사용
* 에러 종류를 구분하여 대응해야할경우, 클래스로 에러객체를 생성하여 에러에대한 상세정보를 포함시켜, catch블록 안에서 에러에 대한 복구를 위한 코드를 짤때 이 상세정보들을 활용할 수 있다

```js
const even = parseInt(prompt('짝수를 입력하세요'));
if (even % 2 !== 0) {
  throw new Error('짝수가 아닙니다.');
}
```
## 비동기식 코드 예외처리 (중요!!!)

### 비동기식 콜백. 에러처리

try블록은 setTimeout 바로 작업큐에넘겨주고 콜스택에서사라진다.
setTimeout이 콜스택으로 들어왔을때 try는 이미 사라졌기떄문에 에러가 발생해도 catch로 에러처리 불가 하다
```js
// 동작안함
try { //setTimeout을 작업큐에 던져주고, 바로 사라진다
  setTimeout(() => {
    throw new Error('에러!');
  });
} catch (e) {
  alert('에러발생'); // 절대 발생안함
}

// 정상동작
setTimeout(() => {
  try {
    throw new Error('에러!');
  } catch (e) {
    console.error('에러발생!!');
  }
}); // 에러발생!! 팝업뜸

```
>비동기콜백 안에서 일어난 에러처리를 하려면, try블록은 **무조건 비동기콜백 안에** 넣어서 사용해야한다

### Promise 에러처리
* Promise객체의 세가지 상태
  1. pending 기다림
  2. fufilled 채워짐
  3. rejected 에러남

`then(pending, rejected)` then은 인자를 두개 받는다
짝수인경우 '짝수입니다'
홀수를 입력한경우 throw에 있는 '짝수가 아닙니다.'
then콜백안에서 return을 하면, 다음promise의 결과값이 된다

promise객체는 함수를 이용하여 값을 채워준다
```js
const p = new Promise(resolve => {
  const even = parseInt(prompt('짝수를 입력하세요'));
  if(even % 2 !== 0){
    throw new Error('짝수가 아닙니다.'); //reject로 해도 실행되긴한다(권장X)
  })
}else {
    resolve(even); //resolve : promise에값을 채워주는 함수
  }
});

//
p.then(even => {
  return '짝수입니다.';
}, e => {
  return e.message;
}).then(alert);
```

throw와 reject의 가장큰 차이점?
reject는 일반함수. 에러가 나도 나머지 코드가 실행됨.
throw는 에러. 에러가 나면 나머지 코드가 실행되지 않음.
return과 비슷하게 함수를 종료시키지만, 훨씬훨씬 강력함 뒤에까지 다 막아버리닌깐

reject보단 throw를 사용하도록!!!

짝수이면 resolve가 even을 반환해주고, 에러가 나면 throw가 e(에러)를 반환해준다


```js
p = new Promise(resolve => {
	setTimeout(() => {
		resolve(3); //3채운 Promise를
	}, 1000) //1초뒤에 생성
})
Promise {<pending>}; // 처음 -> 빈객체반환

//1초뒤 -> 3채워줌
console.log(p); //Promise {<resolved>: 3}
```

```js
p = new Promise(resolve => {
	setTimeout(() => {
		reject(new Error('에러')); //3채운 Promise를
	}, 1000) //1초뒤에 생성
})
Promise {<pending>}; // 처음 -> 빈객체반환

//1초뒤 -> reject
VM564:3 Uncaught ReferenceError: reject is not defined at setTimeout
```
>[promise 추천책](http://www.hanbit.co.kr/store/books/look.php?p_code=E5027975256)

## 비동기 함수
위의 복잡한 try..catch..finally로 예외처리를 간편하게 만들어줌!
```js
async function func() {
  try {
    const res = await fetch('https://nonexistent-domain.nowhere'); //꼭 await해줘야함
  } catch (e) {
    console.log(e.message);
  }
}

func(); // 출력 결과: (e.message) Failed to fetch
```
`async` 비동기 코드이기 때문에, fetch가 완료되기까지 꼭 `await`해줘야 에러를 `catch`할 수 있다.




```js
Promise.resolve() // undefined가 fufilled된 Promise 객체 생성
  .then(() => {
    throw new Error('catch 메소드를 통해 예외 처리를 할 수 있습니다.'); //new Error 에러생성
  })
  .then(() => {
    console.log('이 코드는 실행되지 않습니다.');
  })
  .catch(e => { // Error -> catch로 점프!
    return e.message;
  })
  .then(console.log);

// 만약 Error를 생성하지 않았다면 .then .then이 실행됬을것이다.
```

---
# REST API
>2년전까지 무조건 REST API 통신방식이었지만, 요즘 GraphicQL이 새롭게 떠오르며 통신방식이 분화되고있다.  
*REST-API는 경직된 방식이었다면, GraphicQL은 좀더 유연하다*

[RESTful API Designing Guidelines (번역)](https://wayhome25.github.io/etc/2017/11/26/restful-api-designing-guidelines/)

## npm
필수) 
* node_modules -> .gitignore에 추가해서 업로드 시키지 않는다.
* 설치가 필요한 항목은 목록`package.json`으로 정리해서 올린다

-g 전역으로 설치하는것보다, 폴더에 npx 직접 설치하여 json-server의 정확한 버전을 알려주는게 장기적으로 좋다. 5년이 지나도 10년이 지나도 같은 버전설치되어 똑같이 사용할 수 있기 때문에.

## .gitignore
* 아이디, 비밀번호, 토큰등을 저장해놓고 쓸때, git에는 그 정보들이 올라가지 않도록 .gitignore에 표기해준다.
* 프로젝트와 상관없는 파일도 추가. (ex. npm에러코드등...) 
[프로그램별 gitignore코드 자동생성기](https://www.gitignore.io/api/node%2Cvisualstudiocode)



```js
res = await fetch('http://localhost:3000/comments', {
	method : 'post',
	body: JSON.stringify({body: '댓댓', postId:1}),
	headers: {
		'Content-Type' : 'application/json'
	}
})
```

* 비동기함수는 항상 promise를 반환한다
* return promise하면 promise안에 또 promise를 담는게 아니라, return 하는 promise를 벗겨서 알맹이만 promise통에 담는다.(한겹의 promise이다)













